# Use a standard Node.js image for Strapi
FROM node:22-alpine

# Set the working directory
WORKDIR /workspace

# The 'node:18-alpine' image already includes yarn, so this line is not needed.
# RUN npm install -g yarn

# Expose the default Strapi port
EXPOSE 1338
